### ISSUE TITLE
Wrong order in steps

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-data-sense#37]
Page: [Deploy Cloud Data Sense on prem without internet access](https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-dark-site.html)

Steps 7 and 8 are in wrong order. It must be switched.

7. In the Deploy Data Sense On Premises dialog, copy the provided command and paste it in a text file so you can use it later, and click Close. For example:
sudo ./install.sh -a 12345 -c 27AG75 -t 2198qq --darksite

8. Unzip the installation file on the host machine, for example:
tar -xzf DATASENSE-INSTALLER-V1.16.1.tar.gz

Thx
Holger

**Comment by netapp-tonacki** [comment]
Hi Holger,  Thanks for your comment.  Can you let me know why these steps need to be reversed?

Steps 4-7 are all done in the Data Sense UI.  Then the user goes to the Linux host to unzip the installer.  So I'm not sure why the user would follow steps 4-6 in the UI, then go to the host machine to unzip the installer, then go back to the UI to copy the command.  Also, from what I recall from a while ago, unzipping the installer file actually kicks off the install process - but it's been a while since I tried an install...

Thanks, Tom

**Comment by kholger** [comment]
Hi Tom, thanks for the explanation. We've overseen the comment (paste it in a text file).
The ticket can be closed and sorry for the confusion.
Thx Holger
